/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Animales;

import Controladores.AnimalesController;
import Controladores.IGenericController;
import Modelos.Animales;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author elpow
 */
public class create_form extends javax.swing.JFrame {

    private IGenericController registerController = new AnimalesController();

    /**
     * Creates new form create_form
     */
    public create_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sabana_checkbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        acuario_checkbox = new javax.swing.JCheckBox();
        document_text = new javax.swing.JTextField();
        bosque_checkbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        name_text = new javax.swing.JTextField();
        reptil_rbtn = new javax.swing.JRadioButton();
        ave_rbtn = new javax.swing.JRadioButton();
        mamifero_rbtn = new javax.swing.JRadioButton();
        pantano_checkbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sabana_checkbox.setText("Sabana");

        jLabel1.setText("Documento:");

        acuario_checkbox.setText("Acuario");

        bosque_checkbox.setText("Bosque");

        jLabel2.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setText("ZOOLÓGICO MANZANA VERDE");
        jLabel5.setToolTipText("");

        jLabel3.setText("Posibles hábitats:");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("Sección Administrativa:");
        jLabel6.setToolTipText("");

        jLabel4.setText("Nombre:");

        submit_button.setBackground(new java.awt.Color(102, 102, 0));
        submit_button.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        submit_button.setForeground(new java.awt.Color(255, 255, 255));
        submit_button.setText("Crear Registro");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        reptil_rbtn.setText("Reptil");
        reptil_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reptil_rbtnActionPerformed(evt);
            }
        });

        ave_rbtn.setText("Ave");
        ave_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ave_rbtnActionPerformed(evt);
            }
        });

        mamifero_rbtn.setText("Mamífero");
        mamifero_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mamifero_rbtnActionPerformed(evt);
            }
        });

        pantano_checkbox.setText("Pantanoso");
        pantano_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantano_checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ave_rbtn)
                                .addComponent(reptil_rbtn)
                                .addComponent(mamifero_rbtn)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pantano_checkbox)
                                .addComponent(sabana_checkbox))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bosque_checkbox)
                                .addComponent(acuario_checkbox)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(document_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(document_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(reptil_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ave_rbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mamifero_rbtn)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pantano_checkbox)
                    .addComponent(acuario_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sabana_checkbox)
                    .addComponent(bosque_checkbox))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed

        //Campos de texto
        String Documento = document_text.getText();
        String Nombre = name_text.getText();

        //JCheckBox y JRadioButton
        //Tipo de animal
        boolean Reptil = reptil_rbtn.isSelected();
        boolean Ave = ave_rbtn.isSelected();
        boolean Mamifero = mamifero_rbtn.isSelected();

        //Tipo de hábitat
        boolean Patanoso = pantano_checkbox.isSelected();
        boolean Acuario = acuario_checkbox.isSelected();
        boolean Sabana = sabana_checkbox.isSelected();
        boolean Bosque = bosque_checkbox.isSelected();

        //Validaciones
        if ((Documento.isEmpty() || Nombre.isEmpty())
                || (!Reptil && !Ave && !Mamifero)
                || (!Patanoso && !Acuario && !Sabana && !Bosque)) {
            System.out.println("Por favor defina los parametros correctamente");
            return;
        }

        String TipoAnimalSelect = "";

        if (Reptil) {
            TipoAnimalSelect = "Reptil";
        }
        if (Ave) {
            TipoAnimalSelect = "Ave";
        }
        if (Mamifero) {
            TipoAnimalSelect = "Mamifero";
        }

        List<String> Habitat = new ArrayList<>();

        if (Patanoso) {
            Habitat.add("Pantanoso");
        };
        if (Acuario) {
            Habitat.add("Acuario");
        };
        if (Sabana) {
            Habitat.add("Sabana");
        };
        if (Bosque) {
            Habitat.add("Bosque");
        };

        Animales animalObj = new Animales(
                Nombre,
                Documento,
                TipoAnimalSelect,
                Habitat
        );

        //Llamada al registro
        boolean resp = registerController.crearRegistro(animalObj);

        if (resp) {
            adminAnimalsPage ventana = new adminAnimalsPage();
            ventana.setVisible(true);
            this.setVisible(false);
        } else {
            System.out.println("El registro malio sal");
            return;
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void mamifero_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mamifero_rbtnActionPerformed
        ave_rbtn.setSelected(false);
        reptil_rbtn.setSelected(false);
    }//GEN-LAST:event_mamifero_rbtnActionPerformed

    private void pantano_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantano_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantano_checkboxActionPerformed

    private void reptil_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reptil_rbtnActionPerformed
        ave_rbtn.setSelected(false);
        mamifero_rbtn.setSelected(false);
    }//GEN-LAST:event_reptil_rbtnActionPerformed

    private void ave_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ave_rbtnActionPerformed
        reptil_rbtn.setSelected(false);
        mamifero_rbtn.setSelected(false);
    }//GEN-LAST:event_ave_rbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acuario_checkbox;
    private javax.swing.JRadioButton ave_rbtn;
    private javax.swing.JCheckBox bosque_checkbox;
    private javax.swing.JTextField document_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton mamifero_rbtn;
    private javax.swing.JTextField name_text;
    private javax.swing.JCheckBox pantano_checkbox;
    private javax.swing.JRadioButton reptil_rbtn;
    private javax.swing.JCheckBox sabana_checkbox;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
